name: Running Exporter on Existing Workspace and Source Control

# on:
#   push:
#     branches:
#       - '**'
#     paths: 
#       - 'azure/**'
#     tags-ignore:
#       - 'v*' # this tag type is used for release pipelines
#   schedule:
#     - cron: '30 6 * * 1,3'

jobs:
  run-exporter-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Folders for Terraform Exporter and Repo for exported files
        run: |
          mkdir -p ./databricks-terraform-exporter
          mkdir -p ./exported-db-tf
          
      - name: Download Terraform Exporter and Unzip 
        run: |
          wget https://github.com/databricks/terraform-provider-databricks/releases/download/v1.23.0/terraform-provider-databricks_1.23.0_linux_amd64.zip
          unzip terraform-provider-databricks_* -d ./databricks-terraform-exporter